# Generated by Django 2.2.4 on 2019-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka')], max_length=200),
        ),
    ]
